-- Apply through Supabase SQL editor or adapt into Alembic revision for managed deployment.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, email varchar(320) UNIQUE NOT NULL, username varchar(64) UNIQUE, display_name varchar(128), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS genres (id serial PRIMARY KEY, tmdb_id integer UNIQUE NOT NULL, name varchar(100) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS movies (id serial PRIMARY KEY, tmdb_id integer UNIQUE NOT NULL, title varchar(500) NOT NULL, overview text, release_date date, runtime integer, poster_path varchar(255), backdrop_path varchar(255), vote_average double precision, vote_count integer, popularity double precision, original_language varchar(16), metadata_text text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_movies_title ON movies (title); CREATE INDEX IF NOT EXISTS ix_movies_release_date ON movies (release_date); CREATE INDEX IF NOT EXISTS ix_movies_popularity ON movies (popularity); CREATE INDEX IF NOT EXISTS ix_movies_vote_average ON movies (vote_average);
CREATE TABLE IF NOT EXISTS movie_genres (movie_id integer REFERENCES movies(id) ON DELETE CASCADE, genre_id integer REFERENCES genres(id) ON DELETE CASCADE, PRIMARY KEY(movie_id, genre_id));
CREATE TABLE IF NOT EXISTS ratings (id serial PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, movie_id integer REFERENCES movies(id) ON DELETE CASCADE, rating double precision NOT NULL CHECK(rating >= .5 AND rating <= 5), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, movie_id));
CREATE TABLE IF NOT EXISTS watchlist (id serial PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, movie_id integer REFERENCES movies(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, movie_id));
CREATE TABLE IF NOT EXISTS watch_history (id serial PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE CASCADE, movie_id integer REFERENCES movies(id) ON DELETE CASCADE, watched_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS user_preferences (user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, preferred_genres jsonb NOT NULL DEFAULT '[]', preferred_languages jsonb NOT NULL DEFAULT '[]', onboarding_complete boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS movie_embeddings (movie_id integer PRIMARY KEY REFERENCES movies(id) ON DELETE CASCADE, embedding vector(384) NOT NULL, model_name varchar(255) NOT NULL, embedding_version varchar(64) NOT NULL, source_hash varchar(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_movie_embeddings_cosine ON movie_embeddings USING hnsw (embedding vector_cosine_ops);
CREATE INDEX IF NOT EXISTS ix_ratings_user_movie ON ratings(user_id, movie_id); CREATE INDEX IF NOT EXISTS ix_history_user_movie ON watch_history(user_id, movie_id);
-- Enable RLS for direct Supabase client access; backend uses its controlled database role.
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY; ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY; ALTER TABLE watch_history ENABLE ROW LEVEL SECURITY; ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
