"use client";
import Link from "next/link";
import { Play, Sparkles } from "lucide-react";
import { useMovies, useRecommendations } from "@/hooks/use-api";
import { useAuth } from "@/lib/auth/context";
import { MovieRail } from "@/components/movies/movie-rail";
import { ErrorState, SkeletonGrid } from "@/components/common/states";
import { PageShell } from "@/components/common/page-shell";
export default function HomePage() {
  const trending = useMovies("trending"), popular = useMovies("popular"), topRated = useMovies("topRated"), upcoming = useMovies("upcoming"); const { user } = useAuth(); const recs = useRecommendations();
  const hero = trending.data?.items[0] || popular.data?.items[0];
  return <div><section className="relative min-h-[570px] overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-gradient-to-r from-[#0b0c0f] via-[#0b0c0fcc] to-transparent" />{hero?.backdrop_path && <img src={`https://image.tmdb.org/t/p/original${hero.backdrop_path}`} alt="" className="absolute inset-0 -z-10 h-full w-full object-cover object-center opacity-55" />}<PageShell className="relative flex min-h-[570px] items-end pb-20"><div className="max-w-xl"><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.3em] text-amber-200"><Sparkles size={15} /> Your next favorite awaits</p><h1 className="text-5xl font-semibold leading-[.95] tracking-tight text-white sm:text-7xl">Stories worth<br /><span className="text-amber-200">staying up for.</span></h1><p className="mt-6 line-clamp-3 text-base leading-7 text-white/65">Discover films curated around your taste, from tonight&apos;s trending stories to hidden gems you&apos;ll want to talk about tomorrow.</p><div className="mt-8 flex gap-3"><Link href={hero ? `/movies/${hero.id}` : "/movies"} className="flex items-center gap-2 rounded-full bg-amber-300 px-5 py-3 text-sm font-semibold text-black hover:bg-amber-200"><Play size={16} fill="currentColor" /> Explore now</Link><Link href="/search" className="rounded-full border border-white/15 px-5 py-3 text-sm text-white/80 hover:border-white/40">Search films</Link></div></div></PageShell></section><PageShell>{trending.isLoading ? <SkeletonGrid /> : trending.isError ? <ErrorState /> : <MovieRail title="Trending this week" movies={trending.data.items} href="/movies" />}{popular.isLoading ? <SkeletonGrid /> : popular.isError ? <ErrorState /> : <MovieRail title="Popular right now" movies={popular.data.items} />}{topRated.isLoading ? <SkeletonGrid /> : topRated.isError ? <ErrorState /> : <MovieRail title="The highly rated" movies={topRated.data.items} />}{upcoming.isLoading ? <SkeletonGrid /> : upcoming.isError ? <ErrorState /> : <MovieRail title="Coming soon" movies={upcoming.data.items} />}{user && recs.data && <MovieRail title="Picked for you" movies={recs.data} href="/recommendations" />}</PageShell></div>;
}
