"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation } from "@tanstack/react-query";
import { PageShell } from "@/components/common/page-shell";
import { interactionsApi } from "@/lib/api/interactions";
import { useAuth } from "@/lib/auth/context";
import { useMovies } from "@/hooks/use-api";
export default function OnboardingPage(){const {user}=useAuth();const router=useRouter();const popular=useMovies("popular");const [selected,setSelected]=useState<number[]>([]);const genres=Array.from(new Map((popular.data?.items.flatMap(m=>m.genres)||[]).map(g=>[g.id,g])).values());const save=useMutation({mutationFn:()=>interactionsApi.updatePreferences({preferred_genres:selected,preferred_languages:[],onboarding_complete:true}),onSuccess:()=>router.push("/recommendations")});if(!user)return <PageShell><div className="mx-auto max-w-xl rounded-3xl border border-white/10 bg-white/[.04] p-10 text-center"><h1 className="text-3xl font-semibold">Sign in to personalize CineMatch</h1><button onClick={()=>router.push("/login")} className="mt-6 rounded-full bg-amber-300 px-5 py-3 font-semibold text-black">Sign in</button></div></PageShell>;return <PageShell><div className="mx-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.3em] text-amber-200">A little about you</p><h1 className="mt-4 text-5xl font-semibold tracking-tight">What kind of stories<br/><span className="text-amber-200">pull you in?</span></h1><p className="mt-5 max-w-xl text-white/55">Pick a few genres and we&apos;ll tune your first recommendations. You can change this anytime.</p>{popular.isLoading?<div className="skeleton mt-10 h-24 rounded-2xl"/>:genres.length?<div className="mt-10 flex flex-wrap gap-3">{genres.map(g=>{const active=selected.includes(g.id);return <button key={g.id} onClick={()=>setSelected(v=>active?v.filter(x=>x!==g.id):[...v,g.id])} className={`rounded-full border px-5 py-3 text-sm transition ${active?"border-amber-200 bg-amber-300 text-black":"border-white/10 text-white/65 hover:border-white/40"}`}>{g.name}</button>})}</div>:<p className="mt-10 text-white/50">Genre choices will appear once movie discovery is available.</p>}<button disabled={save.isPending||popular.isLoading} onClick={()=>save.mutate()} className="mt-12 rounded-full bg-amber-300 px-7 py-3 font-semibold text-black disabled:opacity-50">{save.isPending?"Saving…":"Continue to CineMatch"}</button></div></PageShell>}
