"use client";
import Link from "next/link";
import { Clapperboard, LogOut, Menu, Search, UserRound, X } from "lucide-react";
import { useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useAuth } from "@/lib/auth/context";
export function Nav() {
  const { user, loading, logout } = useAuth(); const [open, setOpen] = useState(false); const router = useRouter(); const pathname = usePathname();
  const links = user ? [["Movies", "/movies"], ["Recommendations", "/recommendations"], ["Watchlist", "/watchlist"], ["History", "/history"]] : [["Movies", "/movies"]];
  const signout = () => { logout(); setOpen(false); router.push("/"); };
  return <header className="sticky top-0 z-30 border-b border-white/10 bg-[#0b0c0f]/85 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight" onClick={() => setOpen(false)}><span className="grid size-9 place-items-center rounded-lg bg-amber-300 text-black"><Clapperboard size={20} /></span>Cine<span className="text-amber-200">Match</span></Link><nav className="hidden items-center gap-7 text-sm text-white/65 md:flex">{links.map(([label, href]) => <Link key={href} href={href} className={pathname.startsWith(href) ? "text-amber-200" : "hover:text-white"}>{label}</Link>)}<Link href="/search" className="flex items-center gap-2 hover:text-white"><Search size={16} />Search</Link></nav><div className="hidden items-center gap-3 md:flex">{!loading && (user ? <><Link href="/profile" aria-label="Profile" className="rounded-full border border-white/10 p-2 hover:border-amber-200/50"><UserRound size={17} /></Link><button onClick={signout} className="text-sm text-white/60 hover:text-white"><LogOut size={17} /></button></> : <><Link href="/login" className="text-sm text-white/65 hover:text-white">Sign in</Link><Link href="/signup" className="rounded-full bg-amber-300 px-4 py-2 text-sm font-semibold text-black hover:bg-amber-200">Join CineMatch</Link></>)}</div><button className="rounded-lg border border-white/10 p-2 md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X size={20} /> : <Menu size={20} />}</button></div>{open && <div className="border-t border-white/10 px-5 py-5 md:hidden"><nav className="flex flex-col gap-4 text-white/75">{links.map(([label, href]) => <Link key={href} onClick={() => setOpen(false)} href={href}>{label}</Link>)}<Link onClick={() => setOpen(false)} href="/search">Search</Link>{user ? <><Link onClick={() => setOpen(false)} href="/profile">Profile</Link><button onClick={signout} className="text-left text-amber-200">Sign out</button></> : <><Link onClick={() => setOpen(false)} href="/login">Sign in</Link><Link onClick={() => setOpen(false)} href="/signup" className="text-amber-200">Create account</Link></>}</nav></div>}</header>;
}
